Submitting jobs
parallelworks/docs pull request #5
Opened 2023-01-26 23:38 UTC by OliviaShoup

This branch is for the Submitting Jobs tab in our user guide. This section walks through using workflows and terminals/CLIs to submit jobs, plus includes a section called Common Commands that was originally planned to be its own tab but fits better here. 

_Notes for Matt_
Made these changes after talking on 1/25: 
- Changed `-c` to `--n-tasks-per-node`
- For `-t`, changed the wording to "maximum time" 
- Added an example to fill out the section for `scancel`
- For `sacct`, clarified that it shows completed and running jobs 
- For `scontrol`, clarified that it can be used to manage nodes in addition to jobs

2023-01-27 18:31 UTC, giraffesyo requested changes
All of the instructions in the "Via Terminals" section are for slurm clusters. For on-premise connections we support Slurm or PBS, so we can specify that these instructions are specific to slurm, and maybe we would want another section for PBS?

2023-01-27 18:31 UTC, giraffesyo commented on docs/interacting-with-clusters/submitting-jobs.md
> +When using `watch squeue` or `watch 'sinfo;echo;squeue'`, the `ST` column will show `CF` while the node(s) configure. All of the columns from `JOBID` forward will clear when your job is finished:
Here shouldn't this say All of the "rows", instead of "columns"?

2023-01-27 18:31 UTC, giraffesyo commented on docs/interacting-with-clusters/submitting-jobs.md
> +Once the job is finished, you can check its output with the `std.out` file:
Here we say we use the `std.out` file, but the command shows you using the `simple.out` file. Also, this depends on where the output is sent via the sbatch command, so it's not necessarily in this file depending on their script.

2023-01-27 18:31 UTC, giraffesyo commented on docs/interacting-with-clusters/submitting-jobs.md
> +## Via Workflows
I know this follows the style you used in Logging in to the controller, but after looking at it more I think we should make these fully labeled with what the section is about (not require knowing the page name).. i.e. Submitting jobs via workflows, Submitting jobs from the cluster.

We can change the ones on the logging in to the controller to match this style, that way the sidebars don't look confusing when "Via workflows" and "Via terminal" are next to "Common Commands"

![image](https://user-images.githubusercontent.com/10459772/215166173-35eb17dd-7f5b-4946-80fa-2587b16189c1.png)

2023-01-27 19:24 UTC, mattlongt commented
Regarding the documentation for submitting jobs, I have a couple thoughts:

1. For on-premise clusters, we should generally refer users to the site's own cluster documentation. That documentation would likely cover cluster specific things such as available queues/partitions and available software modules, but would probably also include general user docs for how to use the system.
2. You're right that we should probably clearly mention that the documentation here is specific to cloud clusters. One important caveat when dealing with on-prem systems will be that users very likely won't have root access on the cluster. This would limit the usefulness of commands like `scontrol`, particularly with regards to things like node management when the use of `sudo` would be required. I would say providing cluster management examples is particularly important for our cloud clusters, since users would actually be able to attempt this troubleshooting themselves before submitting a support request.
3. If we want to document useful commands across multiple kinds of schedulers, a table approach might be better. That way we can group similar commands together (ex: `sbatch` for slurm does basically the same thing as `qsub` on PBS). We can do the same thing with scheduler specific environment variables. Here is an example page with the documentation laid out in a similar way: https://www.marquette.edu/high-performance-computing/pbs-to-slurm.php

2023-02-01 16:45 UTC, mattlongt approved these changes
This looks good for a first round, and we can review the suggestions for a future iteration

2023-02-01 16:46 UTC, giraffesyo approved these changes

2023-02-01 16:47 UTC, merged